(setq-default load-path (cons "/usr/local/lib/emacs/site-lisp" load-path))
(global-set-key '[home] 'beginning-of-line)
(global-set-key '[end] 'end-of-line)
(global-set-key '[remove] 'delete-char)
(global-unset-key '[insert])
(line-number-mode t)
;; forth editing
(autoload 'forth-mode "gforth.el")
(setq auto-mode-alist (cons '("\\.fs\\'" . forth-mode) auto-mode-alist))
;Display ISO-Latin-1
(require 'disp-table)
;; Set char codes 160--255 to display as themselves.
;; (Codes 128--159 are the additional control characters.)
;;(standard-display-8bit 160 255)
(standard-display-european t)
(setq dired-move-to-filename-regexp "\\(\\w\\w\\w\\)[ ]+[0-9]+ [ 0-9][0-9][:0-9][0-9][ 0-9] ")
(setq nntp-server-name "news.tuwien.ac.at")
(setq gnus-nntp-server "news.tuwien.ac.at")
(setq tex-dvi-view-command "xdvi")
(load-library "uncompress")
(setq auto-mode-alist (cons '("\\.z$" . uncompress-while-visiting) auto-mode-alist))
;;; Emacs-w3 configuration options
(setq load-path (cons 
		 (expand-file-name "/usr/local/share/emacs/site-lisp")
		 load-path))
(autoload 'w3-preview-this-buffer "w3" "WWW Previewer" t)
(autoload 'w3-follow-url-at-point "w3" "Find document at pt" t)
(autoload 'w3 "w3" "WWW Browser" t)
(autoload 'w3-open-local "w3" "Open local file for WWW browsing" t)
(autoload 'w3-fetch "w3" "Open remote file for WWW browsing" t)
(autoload 'w3-use-hotlist "w3" "Use shortcuts to view WWW docs" t)
(autoload 'w3-show-hotlist "w3" "Use shortcuts to view WWW docs" t)
(autoload 'w3-follow-link "w3" "Follow a hypertext link." t)
(autoload 'w3-batch-fetch "w3" "Batch retrieval of URLs" t)
(autoload 'url-get-url-at-point "url" "Find the url under the cursor" nil)
(autoload 'url-file-attributes  "url" "File attributes of a URL" nil)
(autoload 'url-popup-info "url" "Get info on a URL" t)
(autoload 'url-retrieve   "url" "Retrieve a URL" nil)
(autoload 'url-buffer-visiting "url" "Find buffer visiting a URL." nil)
(autoload 'gopher-dispatch-object "gopher" "Fetch gopher dir" t)
(setq w3-default-homepage "/usr/ftp/pub/index.html#lehre")
(setq w3-reuse-buffers 'yes)
;(setq-default url-be-asynchronous t)
;(setq-default url-proxy-services 
;	      '(("http" . "http://squid.infosys.tuwien.ac.at:3128/")
;		("ftp" . "http://squid.infosys.tuwien.ac.at:3128/")))
(setq url-keep-history t)
(setq-default w3-node-style 'underline)
(setq-default w3-visited-node-style 'underline)
(setq-default w3-active-node-style 'underline)
;;; End of Emacs-w3 configuration options
(server-start)
(setq server-temp-file-regexp "/tmp/")
(put 'save-buffers-kill-emacs 'disabled t)
